spring:
  application:
    name: config-client

  cloud:
    config:
      uri: http://192.168.177.100:8888
      profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://192.168.177.100:8761/eureka/

