server:
  port: 8090
spring:
  application:
    name: eureka-client

eureka:
  client:
    service-url:
      defaultZone: http://192.168.177.100:8761/eureka/
zuul:
  routes:
    hi:
      path: /hi/**
      serviceId: micro-hr

