server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hjsranger/micro-service
          search-paths: config-repo

eureka:
  client:
    service-url:
      defaultZone: http://192.168.177.100:8761/eureka/


